name: CI/CD Data Transfer

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging # You can specify other branches like 'feature/*' if needed.
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #   - name: Checkout Code
    #     uses: actions/checkout@v2

      # - name: Set up Python (Example, adjust for your stack)
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.8'

      # - name: Install Dependencies (Example)
      #   run: |
      #     pip install -r requirements.txt

      - name: Transfer Data (Example)
        run: |
          # Here you can add commands for transferring data, or any necessary build steps
          echo "Transfer data or perform additional actions"

      - name: Push Changes to Another Branch
        run: |
          git config --global user.name "istpl4114"
          git config --global user.email "anjaneyulu.v@istpl.co"
          git checkout -b staging # create or checkout another branch if needed
          git add .
          git commit -m "Automated transfer data"
          git push origin staging
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      # Optionally, handle artifact upload/download, testing, or deployments here
